import matplotlib.pyplot as plt
import numpy as np
import argparse
import os

# This file has been generated by Chat gpt

def read_data(filename):
    """Read data from file with format 'N time lost_space'"""
    N = []
    time = []
    lost_space = []
    
    with open(filename, 'r') as f:
        for line in f:
            values = line.strip().split()
            if len(values) >= 3:
                try:
                    N.append(int(values[0]))
                    time.append(float(values[1]))
                    lost_space.append(float(values[2]))
                except ValueError:
                    print(f"Skipping invalid line: {line}")
    
    return N, time, lost_space

def plot_comparison_graphs(data_dict, output_file=None):
    """Create and display two comparison graphs for multiple algorithms
    
    Args:
        data_dict: Dictionary with algorithm names as keys and (N, time, lost_space) tuples as values
        output_file: Optional file to save the figure
    """
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 7))
    
    # Color cycle for different algorithms
    colors = ['blue', 'red', 'green', 'purple', 'orange', 'brown', 'pink', 'gray']
    markers = ['o', 's', '^', 'D', 'v', '*', 'p', 'x']
    
    for i, (algo_name, (N, time, lost_space)) in enumerate(data_dict.items()):
        color = colors[i % len(colors)]
        marker = markers[i % len(markers)]
        
        # First graph: N vs time
        ax1.plot(N, time, marker=marker, linestyle='-', color=color, label=algo_name)
        
        # Second graph: N vs lost_space
        ax2.plot(N, lost_space, marker=marker, linestyle='-', color=color, label=algo_name)
    
    # Configure first graph (time)
    ax1.set_xlabel('Nombre de fichiers')
    ax1.set_ylabel('Temps (secondes)')
    ax1.set_title("Comparaison du temps d'exécution")
    ax1.grid(True, alpha=0.3)
    ax1.legend()
    ax1.set_xscale('log')
    ax1.set_yscale('log')
    
    # Configure second graph (lost space)
    ax2.set_xlabel('Nombre de fichiers')
    ax2.set_ylabel('Gaspillage')
    ax2.set_title("Comparaison de l'espace perdu")
    ax2.grid(True, alpha=0.3)
    ax2.legend()
    ax2.set_xscale('log')
    ax2.set_yscale('log')
    
    plt.tight_layout()
    
    if output_file:
        plt.savefig(output_file, dpi=300)
    else:
        plt.show()

def extract_algorithm_name(filename):
    """Extract algorithm name from filename"""
    base = os.path.basename(filename)
    return os.path.splitext(base)[0].capitalize()

def main():
    parser = argparse.ArgumentParser(description='Compare bin packing algorithms performance')
    parser.add_argument('input_files', nargs='+', help='Input files with data in format "N time lost_space"')
    parser.add_argument('--output', help='Output file name (if not provided, displays graphs on screen)')
    
    args = parser.parse_args()
    
    # Dictionary to store data for each algorithm
    all_data = {}
    
    for input_file in args.input_files:
        algo_name = extract_algorithm_name(input_file)
        N, time, lost_space = read_data(input_file)
        all_data[algo_name] = (N, time, lost_space)
    
    plot_comparison_graphs(all_data, args.output)

if __name__ == "__main__":
    main()